additional paramters in sequence labelling command line
kermitt2/delft pull request #148
Opened 2022-12-19 07:57 UTC by lfoppiano

This PR adds patience, batch_size and max_sequence_length when not already present, in the applications using sequence labelling.

2023-03-08 17:06 UTC, kermitt2 requested changes

2023-03-08 17:06 UTC, kermitt2 commented on delft/applications/nerTagger.py
> +        configure(architecture, dataset_type, lang, embeddings_name, use_ELMo, max_sequence_length=-1, batch_size=-1, patience=-1)
it should be:
```python
configure(architecture, dataset_type, lang, embeddings_name, use_ELMo, max_sequence_length, batch_size, patience)
```
(it need to use the command line parameters)

2023-03-09 03:55 UTC, lfoppiano commented
Thanks @kermitt2, I've amended the changes following your comments

2023-03-09 08:53 UTC, kermitt2 requested changes

2023-03-09 08:53 UTC, kermitt2 commented on delft/applications/grobidTagger.py
> +        use_ELMo=False, incremental=False, input_model_path=None, patience=5):
I think it should be here:
```
patience=-1
```
otherwise the command line parameter is never considered.

2023-03-09 09:48 UTC, kermitt2 commented
Thank you Luca for your patience for getting me reviewing the PD :D

2023-03-09 09:48 UTC, merged

2023-03-09 10:01 UTC, lfoppiano commented
Thank you!! 👍